import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { CustomEditor } from "../components/Editor/CustomEditor";
import { Editor1 } from "../components/Editor1/Editor1";
import { QuillEditor } from "../components/Quill/Quill";
import TUIEditor from "../components/Toast/ToastEditor";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <CustomEditor /> */}s {/* <Editor1 /> */}
      <TUIEditor onChange={(e) => console.log(e)} />
      {/* <QuillEditor /> */}
    </div>
  );
};

export default Home;
